name: Primeiro Workflow - Relatório de Execução

on:
  push:
    branches:
      - "**"      

jobs:
  executar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Mostrar arquivos do projeto
        run: ls -la

      - name: Executar mensagem de sucesso
        run: echo "Pipeline executada com sucesso!"

      - name: Instalar dependências
        run: npm install
