name: Primeiro Workflow - Relatório de Execução

on:
  push:
    branches:
      - "**"

jobs:
  executar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Listar arquivos da raiz
        run: ls -la

      - name: Listar arquivos da pasta proj-vendas-online
        run: ls -la proj-vendas-online

      - name: Listar arquivos do src
        run: ls -la proj-vendas-online/src

      - name: Listar arquivos das rotas
        run: ls -la proj-vendas-online/src/routes

      - name: Listar arquivos do public
        run: ls -la proj-vendas-online/public

      - name: Instalar dependências do Node
        run: |
          cd proj-vendas-online
          npm install

      - name: Executar mensagem final
        run: echo "Pipeline executada com sucesso!"
